#!/bin/sh

NOW=$(date +"%m%d%Y")
PGMNAME=/usr/bin/HandBrakeCLI
check_errs()
{
    # Function. Parameter 1 is the return code
      # Para. 2 is text to display on failure.
        if [ "${1}" -ne "0" ]; then
          echo "ERROR # ${1} : ${2}"
          # as a bonus, make our script exit with the right error code.
          exit ${1}
        fi
}

BASEPATH=$(dirname "$1")
BASEFILE=$(basename "$1")
FILENAME="${BASEFILE%%.*}"

echo "Starting $NOW"
${PGMNAME} --input "$1" --format mkv --aencoder aac --ab 192 --encoder x264 --x264-preset veryfast --quality 23 --turbo --encoder-level 4.1 --output "$BASEPATH/$FILENAME.mkv"
check_errs $? "Failed to convert file $1"

echo "Removing original file."
rm -f "$1"
check_errs $? "Failed to remove original file $1"

exit