#!/bin/sh

EXT=${SOURCE_EXT}

echo "transcoding all $SOURCE_EXT files to $VIDEO_FORMAT"

for i in *
    do
        if [ "${i}" != "${i%.${EXT}}" ]
            then
                echo "convertible file found: $i"
        fi
done

for i in *
    do
        if [ "${i}" != "${i%.${EXT}}" ]
            then
                echo "converting file $i"
                convert "$i"
        fi
done

